name: "Pull Request Docs Check"

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  user_manual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "user_manual/"
        pre-build-command: pip install -r requirements.txt
        build-command: make html
    - name: Upload static documentation
      uses: actions/upload-artifact@v2.2.4
      with:
        name: User manual.zip
        path: "user_manual/_build/html"
  user_manual-en:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "user_manual/"
        pre-build-command: pip install -r requirements.txt
        build-command: make html-lang-en
  developer_manual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the icons
      shell: bash
      run: make icons-docs-docker
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "developer_manual/"
        pre-build-command: pip install -r requirements.txt
        build-command: make html
    - name: Upload static documentation
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Developer manual.zip
        path: "developer_manual/_build/html/com"
  admin_manual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "admin_manual/"
        pre-build-command: pip install -r requirements.txt
        build-command: make html
    - name: Upload static documentation
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Administration manual.zip
        path: "admin_manual/_build/html/com"
